# Generated by Django 4.1.dev20220126201413 on 2022-03-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('item_price', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
